kind = "mobile"
previewPath = "/"
title = "StreamBox"
version = "1.0.0"
id = "artifacts/streambox"
router = "expo-domain"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 8099

[services.development]
run = "pnpm --filter @workspace/streambox run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/streambox", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/streambox", "run", "serve" ]

[services.env]
PORT = "8099"
BASE_PATH = "/"
