/**
 * Netflix-style design tokens.
 * True black background, Netflix red, white text.
 */

const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#E50914',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#141414',
    cardForeground: '#FFFFFF',
    primary: '#E50914',
    primaryForeground: '#FFFFFF',
    secondary: '#2A2A2A',
    secondaryForeground: '#FFFFFF',
    muted: '#1A1A1A',
    mutedForeground: '#AAAAAA',
    accent: '#FFFFFF',
    accentForeground: '#000000',
    destructive: '#E50914',
    destructiveForeground: '#FFFFFF',
    border: '#333333',
    input: '#1A1A1A',
    surface: '#0A0A0A',
    surfaceRaised: '#141414',
    canvas: '#000000',
    warm: '#AAAAAA',
    success: '#46D369',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#E50914',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#141414',
    cardForeground: '#FFFFFF',
    primary: '#E50914',
    primaryForeground: '#FFFFFF',
    secondary: '#2A2A2A',
    secondaryForeground: '#FFFFFF',
    muted: '#1A1A1A',
    mutedForeground: '#AAAAAA',
    accent: '#FFFFFF',
    accentForeground: '#000000',
    destructive: '#E50914',
    destructiveForeground: '#FFFFFF',
    border: '#333333',
    input: '#1A1A1A',
    surface: '#0A0A0A',
    surfaceRaised: '#141414',
    canvas: '#000000',
    warm: '#AAAAAA',
    success: '#46D369',
  },
  radius: 4,
};

export default colors;
